# Generated by Django 6.0.4 on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desired_direction", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=50)),
                ("preferred_format", models.CharField(max_length=50)),
                ("motivation", models.CharField(max_length=50)),
                ("weekly_hours", models.PositiveIntegerField()),
                ("interest_score", models.FloatField(default=0.0)),
                ("skill_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
